name: scanify
description: "Scan, generate and manage QR codes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.7
  hive: ^2.2.3
  flutter_svg: ^2.2.3
  defer_pointer: ^0.0.2
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  crypto: ^3.0.7
  shared_preferences: ^2.5.5
  flutter_localization: ^0.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pasteboard: ^0.5.0
  external_path: ^2.2.0
  file_picker: ^11.0.2
  device_info_plus: ^12.4.0
  barcode_widget: ^2.0.4
  vibration: ^3.1.8
  audioplayers: ^6.7.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  pretty_qr_code: ^3.6.0
  url_launcher: ^6.3.2
  flutter_contacts: ^2.1.0
  add_2_calendar: ^3.0.1
  fluttertoast: ^9.0.0
  awesome_notifications:  ^0.10.0
  image: ^4.8.0
  flutter_zxing: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  generate: true 
  uses-material-design: true

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf

  assets:
    - assets/sounds/
    - assets/icons/
    - assets/icons/barcodes/
    - assets/fonts/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21