name: qrcode_scanner_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  hive: ^2.2.3
  toastification: ^3.0.3
  skeletonizer: ^2.1.2
  flutter_svg: ^2.2.3
  defer_pointer: ^0.0.2
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  qr_flutter: ^4.1.0
  qr: ^3.0.2
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  crypto: ^3.0.7
  configuration_service: ^1.0.4
  shared_preferences: ^2.5.5
  flutter_localization: ^0.4.0
  flutter_localizations:
    sdk: flutter
  riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: any
  flutter_lints: ^6.0.0
  
flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/