import 'package:scanify/core/l10n/app_localizations.dart'
    show AppLocalizations;

enum ValidationError {
  required,
  noAtSymbol,
  invalidUsername,
  invalidPhone,
  invalidEmail,
  invalidUrl,
  invalidPassword,
  passwordMismatch,
  nameEmpty,
  codeEmpty,
  codeTooShort,
  messageTooLong,
  selectDate,
  latitudeRequired,
  latitudeNotNumber,
  latitudeOutOfRange,
  longitudeRequired,
  longitudeNotNumber,
  longitudeOutOfRange,
  invalidWepKey,
  invalidWpaKey,
  valueRequired,
  invalidYoutube,
  invalidPaypal,
  invalidCode39,
  invalidCodabar,
  invalidEan13,
  invalidEan8,
  invalidItf,
  invalidItfOddDigits,
  invalidItf14,
  invalidUpcA,
  invalidUpcE;

  String message(AppLocalizations l) => switch (this) {
    ValidationError.required => l.validationRequired,
    ValidationError.noAtSymbol => l.validationNoAt,
    ValidationError.invalidUsername => l.validationInvalidUsername,
    ValidationError.invalidPhone => l.validationInvalidPhone,
    ValidationError.invalidEmail => l.validationInvalidEmail,
    ValidationError.invalidUrl => l.validationInvalidUrl,
    ValidationError.invalidPassword => l.validationInvalidPassword,
    ValidationError.passwordMismatch => l.validationPasswordMismatch,
    ValidationError.nameEmpty => l.validationNameEmpty,
    ValidationError.codeEmpty => l.validationCodeEmpty,
    ValidationError.codeTooShort => l.validationCodeTooShort,
    ValidationError.messageTooLong => l.validationMessageTooLong,
    ValidationError.selectDate => l.validationSelectDate,
    ValidationError.latitudeRequired => l.validationLatitudeRequired,
    ValidationError.latitudeNotNumber => l.validationLatitudeNotNumber,
    ValidationError.latitudeOutOfRange => l.validationLatitudeOutOfRange,
    ValidationError.longitudeRequired => l.validationLongitudeRequired,
    ValidationError.longitudeNotNumber => l.validationLongitudeNotNumber,
    ValidationError.longitudeOutOfRange => l.validationLongitudeOutOfRange,
    ValidationError.invalidWepKey => l.validationInvalidWepKey,
    ValidationError.invalidWpaKey => l.validationInvalidWpaKey,
    ValidationError.valueRequired => l.validationValueRequired,
    ValidationError.invalidYoutube => l.validationInvalidYoutube,
    ValidationError.invalidPaypal => l.validationInvalidPaypal,
    ValidationError.invalidCode39 => l.validationInvalidCode39,
    ValidationError.invalidCodabar => l.validationInvalidCodabar,
    ValidationError.invalidEan13 => l.validationInvalidEan13,
    ValidationError.invalidEan8 => l.validationInvalidEan8,
    ValidationError.invalidItf => l.validationInvalidItf,
    ValidationError.invalidItfOddDigits => l.validationInvalidItfOddDigits,
    ValidationError.invalidItf14 => l.validationInvalidItf14,
    ValidationError.invalidUpcA => l.validationInvalidUpcA,
    ValidationError.invalidUpcE => l.validationInvalidUpcE,
  };
}
